Repository lion-packages/files, pull requests merged in 2024-11, with the labels that each got.

#7 Project Documentation
  .gitignore
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#8 getNamespaceFromFile and getFiles added
  .gitignore
  composer.json
  composer.lock
  src/LionFiles/Store.php
  test-report.sh
  tests/Providers/CustomClassProvider.php
  tests/StoreTest.php
Labels: enhancement, tests

#9 Support with PHP 8.4
  Dockerfile
Labels: continuous integration
