Repository lion-packages/files, pull requests merged in 2025-04, with the labels that each got.

#22 Installation of Infection
  composer.json
  infection.json
  src/LionFiles/Store.php
  src/LionFiles/Zip.php
  tests/StoreTest.php
  tests/ZipTest.php
Labels: dependencies, tests

#23 Infection is integrated
  .github/workflows/php.yml
  Dockerfile
Labels: continuous integration

#24 Added StyleCI configuration
  .styleci.yml
  Dockerfile
Labels: continuous integration

#25 Create method is added
  src/LionFiles/Store.php
  tests/Providers/StoreProviderTrait.php
  tests/StoreTest.php
Labels: enhancement, tests

#27 Adding a condition to run test coverage in Github Actions (Pull Request)
  .github/workflows/php.yml
Labels: continuous integration

#28 Define the execution time for Github Actions
  .github/workflows/php.yml
Labels: continuous integration

#30 Modify error responses by file-error
  src/LionFiles/Store.php
  tests/StoreTest.php
Labels: enhancement
