Repository lion-packages/files, pull requests merged in 2025-03, with the labels that each got.

#16 Update PHPUnit v12
  Dockerfile
  composer.json
  phpunit.xml
Labels: dependencies

#17 add cache in workflow
  .github/workflows/php.yml
Labels: continuous integration

#18 Update README.md
  .github/README.md
Labels: documentation

#19 PHPLint is integrated
  .github/workflows/php.yml
  .gitignore
  composer.json
Labels: continuous integration, dependencies

#20 Added dependency-review in Github Actions
  .github/workflows/php.yml
Labels: continuous integration

#21 Added dependabot
  .github/dependabot.yml
Labels: continuous integration
