Repository lion-packages/files, pull requests merged in 2025-02, with the labels that each got.

#12 Documentation files have been relocated
  .github/CHANGELOG.md
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/README.md
  .gitignore
  composer.lock
  test-report.sh
  test.sh
Labels: documentation

#13 Standardization with PHPStan and PHP_CodeSniffer is added
  composer.json
  src/LionFiles/Store.php
  src/LionFiles/Zip.php
  tests/StoreTest.php
  tests/ZipTest.php
Labels: documentation, dependencies, standardization

#14 Updated Github Actions settings
  .github/workflows/php.yml
Labels: continuous integration

#15 Update CODE_OF_CONDUCT.md
  .github/CODE_OF_CONDUCT.md
Labels: documentation
